import {
  RiCalendarEventLine,
  RiGithubLine,
  RiGitRepositoryLine,
  RiLinkedinLine,
  RiTwitterXLine,
  RiOpenaiFill,
  RiClaudeFill,
} from "@remixicon/react";
import {
  ArrowDown,
  ArrowUpRight,
  ArrowUp,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Download,
  Envelope,
  Expand,
  DarkLight,
} from "reicon-react";

export const Icons = {
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  CalendarEvent: RiCalendarEventLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Claude: RiClaudeFill,
  Download,
  Expand,
  GitRepository: RiGitRepositoryLine,
  Github: RiGithubLine,
  Linkedin: RiLinkedinLine,
  Mail: Envelope,
  OpenAI: RiOpenaiFill,
  Theme: DarkLight,
  Twitter: RiTwitterXLine,
};
